### ISSUE TITLE
Videos Thumbnails

### ISSUE THREAD

**Issue by sthrs** [ddrayne/youtubeplaylist#1]
Hi Dan,

I was wondering how to make the video thumbs (the one on the video before hit play button) fits perfectly. I had to resize the video size to fits my layout, width: 300, h:183, but it keeps in small size http://d.pr/T47T any ideas?

**Comment by ddrayne** [comment]
Hi Svw

You'd probably need to use the larger thumbs, then position them with css.  Have you got a test page or files?

You might also want to check out my mtgallery repo, which does something a little different with thumbnails to ensure they fit within ratio.

Cheers,

Dan

(p.s Sorry for the delay, I've been on holiday...)

**Comment by sthrs** [comment]
Here's a test page http://cl.ly/9ZCl
mtgallery seems not working for me, it's just a list of links, can't see the gallery view, is that correct? 

Thanks Dan

**Comment by ddrayne** [comment]
Hi Again

I'm getting js errors on that page so I think the plugin is having trouble running there, but the thumbnails you're seeing are coming from youtube in this case so it's unfortunately not something we have control over.

I'll have a look over at mtgallery, cheers!

Dan
