### ISSUE TITLE
showRelated=false not being passed - new player

### ISSUE THREAD

**Issue by Sadie** [ddrayne/youtubeplaylist#5]
Plugin works beautifully  but cannot get showRelated to be false, despite settings.  I'm talking about the generated iframe code that displays either Flash or HTML5, depending upon the browser capabilities.

I hard-coded around it by changing line 67 of the .js file to
html += ' src="http://www.youtube.com/embed/'+ id + "?rel=0" +'" frameborder="0"';

but would love to know the correct way to pass that parameter.  Thanks for any input.

**Comment by ddrayne** [comment]
Hi Sadie

This is fixed in b34cb8c064479d568494fea36f69d075591a18e5.  Please let me know if you continue to have issues!

Dam
